//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadekoBot.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResponseStrings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NadekoBot.Resources.ResponseStrings", typeof(ResponseStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to That base is already claimed or destroyed..
        /// </summary>
        public static string clashofclans_base_already_claimed {
            get {
                return ResourceManager.GetString("clashofclans_base_already_claimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to That base is already destroyed..
        /// </summary>
        public static string clashofclans_base_already_destroyed {
            get {
                return ResourceManager.GetString("clashofclans_base_already_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to That base is not claimed..
        /// </summary>
        public static string clashofclans_base_already_unclaimed {
            get {
                return ResourceManager.GetString("clashofclans_base_already_unclaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to **DESTROYED** base #{0} in a war against {1}.
        /// </summary>
        public static string clashofclans_base_destroyed {
            get {
                return ResourceManager.GetString("clashofclans_base_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has **UNCLAIMED** base #{1} in a war against {2}.
        /// </summary>
        public static string clashofclans_base_unclaimed {
            get {
                return ResourceManager.GetString("clashofclans_base_unclaimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Claim from @{0} for a war against {1} has expired..
        /// </summary>
        public static string clashofclans_claim_expired {
            get {
                return ResourceManager.GetString("clashofclans_claim_expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} claimed a base #{1} in a war against {2}.
        /// </summary>
        public static string clashofclans_claimed_base {
            get {
                return ResourceManager.GetString("clashofclans_claimed_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to @{0} You already claimed base #{1}. You can&apos;t claim a new one..
        /// </summary>
        public static string clashofclans_claimed_other {
            get {
                return ResourceManager.GetString("clashofclans_claimed_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Enemy.
        /// </summary>
        public static string clashofclans_enemy {
            get {
                return ResourceManager.GetString("clashofclans_enemy", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Info about war against {0}.
        /// </summary>
        public static string clashofclans_info_about_war {
            get {
                return ResourceManager.GetString("clashofclans_info_about_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Invalid base number..
        /// </summary>
        public static string clashofclans_invalid_base_number {
            get {
                return ResourceManager.GetString("clashofclans_invalid_base_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Not a Valid war size..
        /// </summary>
        public static string clashofclans_invalid_size {
            get {
                return ResourceManager.GetString("clashofclans_invalid_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to List Of Active Wars.
        /// </summary>
        public static string clashofclans_list_active_wars {
            get {
                return ResourceManager.GetString("clashofclans_list_active_wars", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No active wars..
        /// </summary>
        public static string clashofclans_no_active_wars {
            get {
                return ResourceManager.GetString("clashofclans_no_active_wars", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to not claimed.
        /// </summary>
        public static string clashofclans_not_claimed {
            get {
                return ResourceManager.GetString("clashofclans_not_claimed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not participating in that war..
        /// </summary>
        public static string clashofclans_not_partic {
            get {
                return ResourceManager.GetString("clashofclans_not_partic", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to @{0} You are either not participating in that war, or that base is already destroyed..
        /// </summary>
        public static string clashofclans_not_partic_or_destroyed {
            get {
                return ResourceManager.GetString("clashofclans_not_partic_or_destroyed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Size.
        /// </summary>
        public static string clashofclans_size {
            get {
                return ResourceManager.GetString("clashofclans_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to War against {0} has already started..
        /// </summary>
        public static string clashofclans_war_already_started {
            get {
                return ResourceManager.GetString("clashofclans_war_already_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to War against {0} created..
        /// </summary>
        public static string clashofclans_war_created {
            get {
                return ResourceManager.GetString("clashofclans_war_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to War against {0} ended..
        /// </summary>
        public static string clashofclans_war_ended {
            get {
                return ResourceManager.GetString("clashofclans_war_ended", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to That war does not exist..
        /// </summary>
        public static string clashofclans_war_not_exist {
            get {
                return ResourceManager.GetString("clashofclans_war_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to War against {0} started!.
        /// </summary>
        public static string clashofclans_war_started {
            get {
                return ResourceManager.GetString("clashofclans_war_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All custom reaction stats cleared..
        /// </summary>
        public static string customreactions_all_stats_cleared {
            get {
                return ResourceManager.GetString("customreactions_all_stats_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Custom Reaction deleted.
        /// </summary>
        public static string customreactions_deleted {
            get {
                return ResourceManager.GetString("customreactions_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Insufficient permissions. Requires Bot ownership for global custom reactions, and Administrator for server custom reactions..
        /// </summary>
        public static string customreactions_insuff_perms {
            get {
                return ResourceManager.GetString("customreactions_insuff_perms", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to List of all custom reactions.
        /// </summary>
        public static string customreactions_list_all {
            get {
                return ResourceManager.GetString("customreactions_list_all", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Custom Reactions.
        /// </summary>
        public static string customreactions_name {
            get {
                return ResourceManager.GetString("customreactions_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to New Custom Reaction.
        /// </summary>
        public static string customreactions_new_cust_react {
            get {
                return ResourceManager.GetString("customreactions_new_cust_react", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No custom reactions found..
        /// </summary>
        public static string customreactions_no_found {
            get {
                return ResourceManager.GetString("customreactions_no_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No custom reaction found with that id..
        /// </summary>
        public static string customreactions_no_found_id {
            get {
                return ResourceManager.GetString("customreactions_no_found_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Response.
        /// </summary>
        public static string customreactions_response {
            get {
                return ResourceManager.GetString("customreactions_response", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Custom Reaction Stats.
        /// </summary>
        public static string customreactions_stats {
            get {
                return ResourceManager.GetString("customreactions_stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Stats cleared for {0} custom reaction..
        /// </summary>
        public static string customreactions_stats_cleared {
            get {
                return ResourceManager.GetString("customreactions_stats_cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No stats for that trigger found, no action taken..
        /// </summary>
        public static string customreactions_stats_not_found {
            get {
                return ResourceManager.GetString("customreactions_stats_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Trigger.
        /// </summary>
        public static string customreactions_trigger {
            get {
                return ResourceManager.GetString("customreactions_trigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has already fainted..
        /// </summary>
        public static string pokemon_already_fainted {
            get {
                return ResourceManager.GetString("pokemon_already_fainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} already has full HP..
        /// </summary>
        public static string pokemon_already_full {
            get {
                return ResourceManager.GetString("pokemon_already_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your type is already {0}.
        /// </summary>
        public static string pokemon_already_that_type {
            get {
                return ResourceManager.GetString("pokemon_already_that_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to used {0}{1} on {2}{3} for {4} damage..
        /// </summary>
        public static string pokemon_attack {
            get {
                return ResourceManager.GetString("pokemon_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You can&apos;t attack again without retaliation!.
        /// </summary>
        public static string pokemon_cant_attack_again {
            get {
                return ResourceManager.GetString("pokemon_cant_attack_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You can&apos;t attack yourself..
        /// </summary>
        public static string pokemon_cant_attack_yourself {
            get {
                return ResourceManager.GetString("pokemon_cant_attack_yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has fainted!.
        /// </summary>
        public static string pokemon_fainted {
            get {
                return ResourceManager.GetString("pokemon_fainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to healed {0} with one {1}.
        /// </summary>
        public static string pokemon_healed {
            get {
                return ResourceManager.GetString("pokemon_healed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has {1} HP remaining..
        /// </summary>
        public static string pokemon_hp_remaining {
            get {
                return ResourceManager.GetString("pokemon_hp_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You can&apos;t use {0}. Type `{1}ml` to see a list of moves you can use..
        /// </summary>
        public static string pokemon_invalid_move {
            get {
                return ResourceManager.GetString("pokemon_invalid_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Movelist for {0} type.
        /// </summary>
        public static string pokemon_moves {
            get {
                return ResourceManager.GetString("pokemon_moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You don&apos;t have enough {0}.
        /// </summary>
        public static string pokemon_no_currency {
            get {
                return ResourceManager.GetString("pokemon_no_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to It&apos;s not effective..
        /// </summary>
        public static string pokemon_not_effective {
            get {
                return ResourceManager.GetString("pokemon_not_effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to revived {0} with one {1}.
        /// </summary>
        public static string pokemon_revive_other {
            get {
                return ResourceManager.GetString("pokemon_revive_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You revived yourself with one {0}.
        /// </summary>
        public static string pokemon_revive_yourself {
            get {
                return ResourceManager.GetString("pokemon_revive_yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your type has been changed to {0} for a {1}.
        /// </summary>
        public static string pokemon_settype_success {
            get {
                return ResourceManager.GetString("pokemon_settype_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to It&apos;s somewhat effective..
        /// </summary>
        public static string pokemon_somewhat_effective {
            get {
                return ResourceManager.GetString("pokemon_somewhat_effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to It&apos;s super effective!.
        /// </summary>
        public static string pokemon_super_effective {
            get {
                return ResourceManager.GetString("pokemon_super_effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You used too many moves in a row, so you can&apos;t move!.
        /// </summary>
        public static string pokemon_too_many_moves {
            get {
                return ResourceManager.GetString("pokemon_too_many_moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type of {0} is {1}.
        /// </summary>
        public static string pokemon_type_of_user {
            get {
                return ResourceManager.GetString("pokemon_type_of_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User not found..
        /// </summary>
        public static string pokemon_user_not_found {
            get {
                return ResourceManager.GetString("pokemon_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You fainted, so you are not able to move!.
        /// </summary>
        public static string pokemon_you_fainted {
            get {
                return ResourceManager.GetString("pokemon_you_fainted", resourceCulture);
            }
        }
    }
}
