//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NadekoBot.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResponseStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal ResponseStrings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NadekoBot.Resources.ResponseStrings", typeof(ResponseStrings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has already fainted..
        /// </summary>
        public static string pokemon_already_fainted {
            get {
                return ResourceManager.GetString("pokemon_already_fainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {1} already has full HP..
        /// </summary>
        public static string pokemon_already_full {
            get {
                return ResourceManager.GetString("pokemon_already_full", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your type is already {0}.
        /// </summary>
        public static string pokemon_already_that_type {
            get {
                return ResourceManager.GetString("pokemon_already_that_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to used **{0}**{1} on {2}{3} for **{4}** damage..
        /// </summary>
        public static string pokemon_attack {
            get {
                return ResourceManager.GetString("pokemon_attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You can&apos;t attack again without retaliation!.
        /// </summary>
        public static string pokemon_cant_attack_again {
            get {
                return ResourceManager.GetString("pokemon_cant_attack_again", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You can&apos;t attack yourself..
        /// </summary>
        public static string pokemon_cant_attack_yourself {
            get {
                return ResourceManager.GetString("pokemon_cant_attack_yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has fainted!.
        /// </summary>
        public static string pokemon_fainted {
            get {
                return ResourceManager.GetString("pokemon_fainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} has {1} HP remaining..
        /// </summary>
        public static string pokemon_hp_remaining {
            get {
                return ResourceManager.GetString("pokemon_hp_remaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You are not able to use **{0}**. Type {1}ml to see a list of moves you can use..
        /// </summary>
        public static string pokemon_invalid_move {
            get {
                return ResourceManager.GetString("pokemon_invalid_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Movelist for &quot;{0}&quot; type.
        /// </summary>
        public static string pokemon_moves {
            get {
                return ResourceManager.GetString("pokemon_moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You don&apos;t have enough {0}.
        /// </summary>
        public static string pokemon_no_currency {
            get {
                return ResourceManager.GetString("pokemon_no_currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to It&apos;s not effective..
        /// </summary>
        public static string pokemon_not_effective {
            get {
                return ResourceManager.GetString("pokemon_not_effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to revived {0} with one {1}.
        /// </summary>
        public static string pokemon_revive_other {
            get {
                return ResourceManager.GetString("pokemon_revive_other", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You revived yourself with one {0}.
        /// </summary>
        public static string pokemon_revive_yourself {
            get {
                return ResourceManager.GetString("pokemon_revive_yourself", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Your type has been changed to {0} for a {1}.
        /// </summary>
        public static string pokemon_settype_success {
            get {
                return ResourceManager.GetString("pokemon_settype_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to It&apos;s somewhat effective..
        /// </summary>
        public static string pokemon_somewhat_effective {
            get {
                return ResourceManager.GetString("pokemon_somewhat_effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to It&apos;s super effective!.
        /// </summary>
        public static string pokemon_super_effective {
            get {
                return ResourceManager.GetString("pokemon_super_effective", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You used too many moves in a row, so you can&apos;t move!.
        /// </summary>
        public static string pokemon_too_many_moves {
            get {
                return ResourceManager.GetString("pokemon_too_many_moves", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Type of {0} is **{1}**.
        /// </summary>
        public static string pokemon_type_of_user {
            get {
                return ResourceManager.GetString("pokemon_type_of_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User not found..
        /// </summary>
        public static string pokemon_user_not_found {
            get {
                return ResourceManager.GetString("pokemon_user_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You fainted, so you are not able to move!.
        /// </summary>
        public static string pokemon_you_fainted {
            get {
                return ResourceManager.GetString("pokemon_you_fainted", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to healed {0} with one {1}.
        /// </summary>
        public static string pokmeon_healed {
            get {
                return ResourceManager.GetString("pokmeon_healed", resourceCulture);
            }
        }
    }
}
