namespace NadekoBot.Common
{
    public enum BotConfigEditType
    {
        BetflipMultiplier,
        Betroll100Multiplier,
        Betroll67Multiplier,
        Betroll91Multiplier,
        CurrencyGenerationChance,
        CurrencyGenerationCooldown,
        CurrencyName,
        CurrencyPluralName,
        CurrencySign,
        DmHelpString,
        HelpString,
        CurrencyDropAmount,
        CurrencyDropAmountMax,
        TriviaCurrencyReward,
        XpPerMessage,
        XpMinutesTimeout,
        PatreonCurrencyPerCent,
        MinWaifuPrice,
        WaifuGiftMultiplier,
        MinimumTriviaWinReq,
        MinBet,
        MaxBet,
        ErrorColor,
        OkColor,
        ConsoleOutputType,
    }
}
